engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        # mass_threshold: 30
      - javascript
    exclude_paths:
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
  eslint:
    enabled: true
  fixme:
    enabled: true
    exclude_paths:
    - 'public/build/bundle.js'
    - '.codeclimate.yml'
    config:
      strings:
      # Removed TODO from this list, as we want to allow TODOs in the codebase
      - FIXME
      - HACK
      - BUG
      - XXX
  reek:
    enabled: true
    exclude_paths:
    - 'spec/**/*'
    - 'db/migrate/*'
    - 'lib/i18n_override.rb'
  rubocop:
    enabled: true
  scss-lint:
    enabled: true

ratings:
  paths:
  - app/**
  - lib/**
  - '**.rb'
  - '**.go'
